# Generated by Django 5.0.2 on 2025-06-16 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pokemon_id",
                    models.IntegerField(unique=True, verbose_name="宝可梦编号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("name_en", models.CharField(max_length=100, verbose_name="英文名")),
                ("height", models.FloatField(verbose_name="身高(m)")),
                ("weight", models.FloatField(verbose_name="体重(kg)")),
                ("image_url", models.URLField(verbose_name="图片URL")),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "宝可梦",
                "verbose_name_plural": "宝可梦",
                "ordering": ["pokemon_id"],
            },
        ),
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="属性名称"
                    ),
                ),
                ("color", models.CharField(max_length=7, verbose_name="属性颜色")),
            ],
            options={
                "verbose_name": "属性",
                "verbose_name_plural": "属性",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="pokemon.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏",
                "unique_together": {("user", "pokemon")},
            },
        ),
        migrations.CreateModel(
            name="PokemonTypeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.IntegerField(verbose_name="属性槽位")),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="pokemon.pokemon",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokemon.pokemontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "宝可梦属性关系",
                "verbose_name_plural": "宝可梦属性关系",
                "unique_together": {("pokemon", "slot")},
            },
        ),
    ]
